IonicaBizau/git-url-parse

CONTRIBUTING.md
README.md
example/index.js
lib/index.js
package.json
test/index.js

I was building a bunch of little libraries to support a better parsing:
- [`git-up`](https://github.com/IonicaBizau/node-git-up)
- [`is-ssh`](https://github.com/IonicaBizau/node-is-ssh)
- [`parse-url`](https://github.com/IonicaBizau/node-parse-url)
- [`protocols`](https://github.com/IonicaBizau/node-protocols)
Honestly, when I wrote this library I totally forgot that the git url is not only in `host/owner/name` format but it could be any valid git url. In fact, I didn't consider the custom git servers for example.
However, this should be gone now. Using [`git-up`](https://github.com/IonicaBizau/node-git-up), this library should support more providers. Explicitly, `git-url-parse` supports the common git providers urls (if you have a limitation, …

Use git-up

---

lib/index.js

@IonicaBizau 
I'm building a utility that leverages this library but must run on an older version of Node (0.10 and 0.12). Changing this one line makes it work.  Normally I would not make a change like this but given it looks like the only use of ES2015 in the file, it seems harmless.

Add compatibility for older versions of node

---

README.md
package.json

- Updated the README.md following the new template. :memo:
- Use [`babel-it`](https://github.com/IonicaBizau/babel-it) to babelify the code, so the module is now compatible with older versions of Node.js.

git-url-parse 6.0.3

---

README.md
package.json

- Fix the [Patreon link](https://patreon.com/ionicabizau) in the README.md file. :memo:

git-url-parse 6.0.7

---

lib/index.js
test/index.js

This will add a specified port to a stringified url when it is relevant. This should fix the case where if you parse an ssh url with a custom port, then stringify the result, the port will be lost.
``` javascript
import GitUrlParse from 'git-url-parse';
const url = GitUrlParse('ssh://git@mygitserver.com:1234/user/repo.git');
GitUrlParse.stringify(url);  // git@mygitserver.com:user/repo.git  <-- port is missing
// With change
GitUrlParse.stringify(url);  // ssh://git@mygitserver.com:1234/user/repo.git'
```
It should also fix the problem for custom ports on http/https urls, though I believe parsing those improperly determines those urls as being `ssh` protocols.

Adding the port for a stringified url if it is provided

---

lib/index.js
test/index.js

This will use whatever username is specified for ssh urls instead of the hardcoded `git` value.
```
import GitUrlParse from 'git-url-parse';
const url = GitUrlParse('ssh://myuser@mygitserver.com/owner/repo.git');
GitUrlParse.stringify(url); // 'git@mygitserver.com:owner/repo.git' <-- wrong username
// With change
GitUrlParse.stringify(url); // 'myuser@mygitserver.com:owner/repo.git'
```
I also added a change that will allow multiple protocols (`ssh+git`) to be stringified properly even if the type isn't specified in the method call.

Adds support for non-git usernames in stringified url

---

example/index.js
lib/index.js
test/index.js

This is a first shot at ref / filepath capturing. Still a WIP but is this in the right direction?
to do:
will close #41

adding ref capturing

---

lib/index.js
test/index.js

Fixes: https://github.com/IonicaBizau/git-url-parse/issues/58
VSTS legacy URLs used to include the string `DefaultCollection` in the URL path, and I failed to handle that case when I originally implemented VSTS URL parsing. This should fix the parsing of these legacy URLs.

Handle VSTS legacy URLs

---

lib/index.js
test/index.js

Fix #67, Fix #70
This fix both the parsing and stringifying of VSTS URL, in particular:
- Parse the `full_name` based on the different VSTS URL format
- Fix parsing of `organization`
- Preserve the original URL when stringifying
- Add tests for `toString()`
I'm not familiar with VSTS but what I found in the docs seems to be covered by the tests.
/cc @roger199585

Fix VSTS URL parsing and stringifying

---

lib/index.js
test/index.js

Fix #69
In the parsed result, `git_suffix` is now set to `true` if the URL ends with `.git`.
Users can still change its value before calling `toString()`

Fix parsing of git_suffix

---

package.json

Fix parsing of `source` with 2 parts SLD
/cc #80 Thanks @pvdlg!

git-url-parse 10.0.1

---

lib/index.js
test/index.js

Gitlab introduced the [/-/ scope][1] to avoid ambiguities when routing.
This means that some URLs now contain a further element in the path and
parsing breaks for these URLs.
This fix takes the new potential element in the path into account.
[1]: https://docs.gitlab.com/ee/development/routing.html
Closes #107

Fix parsing of GitLab URLs with /-/ scope

---

lib/index.js
test/index.js

This adds support for setting the `filepath` property when the `path` query parameter is present.
Closes #110

Add filepath support for Azure DevOps

---

lib/index.js
test/index.js

Add Bitbucket Server support. When this PR is completed it will solve #97

Add support for Bitbucket Server

---

lib/index.js
test/index.js

When we have to parse a Bitbucket Server URL that ends with `browse` such as `https://bitbucket.mycompany.com/projects/some-owner/repos/some-repo-name/browse` which is a valid URL, the actual result is:
- `name` = `browse`;
- `owner` = `projects/some-owner/repos/some-repo-name`.
The expected result should be:
- `name` = `some-repo-name`;
- `owner` = `some-owner`.

Fix Bitbucket Server URL when it only ends with /browse

---

lib/index.js
test/index.js

This pull request aims to add support for providing a correct clone url for Bitbucket Server when you are calling gitInfo.toString("https")`
I have used the `source` property for specifying that its a bitbucket-server instance, however I would love some feedback on that solution. In addition, giving a correct clone https url based on an ssh clone address is difficult and is therefore out of scope for this PR.

Add support for mapping Bitbucket Server clone urls

---

lib/index.js
test/index.js

Parses URLs like `https://dev.azure.com/MyOrganization/MyProject/_git/MyRepo?path=%2Ftest%2Findex.js&version=GBother` in which `version=GB<branch>` is the git branch.

add Azure DevOps parsing of git branch

---

lib/index.js
test/index.js

This pull request will enhance the support for Bitbucket Server http(s) urls.
It will parse the `/commits/<sha1|branch>` endpoints. It will also correctly parse the owner and name when you only have the root url to a repository e.g. https://bitbucket.mycompany.com/projects/owner/repos/name

Add support for Bitbucket Server repository root and commit endpoints

---

lib/index.js
test/index.js

#128 introduced a bug when parsing Bitbucket Server file urls for files located in a subfolder.
This pull request will make sure that we correctly get the full `filepath` instead of only the first folder.

Fix parsing Bitbucket Server urls with files located in subfolders

---

README.md
lib/index.js
package.json
test/index.js

- Fix shorthand urls. Fix #147.
- Custom SSH User support. /cc #142 -- thanks @privatenumber!
There are **breaking changes** due to the update to `parse-url@^8.0.0`. :sparkles:

git-url-parse 13.0.0

---

lib/index.js
test/index.js

Hi 👋 
In order to have this link parsed correctly:
```
https://github.com/React95/React95/edit/master/README.md
```
we need to support the `edit` file path type. 
Here is a link for the issue I'm talking about:
https://stackblitz.com/edit/vitejs-vite-gv8qby?file=src%2Fmain.ts&terminal=dev

Add `edit` filepathtype support

---

lib/index.js
test/index.js

As the path's components, especially owner and repository names, are decoded for all hosting environments, I re-encoded the value in the `default` implementation where the path is built. 
fixes #155 .

re-encode owner and repository in stringify

---

lib/index.js
test/index.js

Fixes: https://github.com/IonicaBizau/git-url-parse/issues/133
@IonicaBizau Can you please review this PR?

fixed name and organization issue when parsing on the issue URL

---

lib/index.js
test/index.js

Although this _does_ fix the problem I'm not 100% confident in the correctness of this solution.
Fixes #167

fix parsing with 'blob' in file path

---

lib/index.js
test/index.js

Fixes https://github.com/IonicaBizau/git-url-parse/issues/104
Workaround for URLs that contain branches with slashes. 
If user wants to identify the branch, he should pass all branch names of the project as part of `refs` parameter

Fixed parsing branch with slashes in its name

---

package.json
test/index.js

This fix allows the library to handle SSH URLs with URL-encoded spaces (i.e., `%20`), including VSTS URLs.
This was done by upgrading the _git-up_ library to 8.0.0.
This will fix #162

#162: handle SSH URLs with URL-encoded spaces
