IonicaBizau/git-url-parse

LICENSE, README.md, package.json
- Added package.json
- Improved the documentation.
- Integrated **[json2md](https://github.com/IonicaBizau/json2md)** with **[blah](https://github.com/IonicaBizau/blah)** to get the best flexibility in generating documentation. :dizzy:
- Relicense to [MIT and link to the license](http://showalicense.com). :heart:
Regarding the integration of **json2md** into **blah**, [read this blog post I wrote](http://ionicabizau.net/blog/27-how-to-convert-json-to-markdown-using-json2md).
=> git-url-parse 4.2.0 Improved documentation

LICENSE, README.md, package.json
- Added badges :tada:
- [PayPal Donations](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RVXDDLKKLQRJW)
- npm downloads
- npm version
- Travis (if there are tests)
- [CodeMentor](https://www.codementor.io/johnnyb?utm_source=github&utm_medium=button&utm_term=johnnyb&utm_campaign=github)–you can ping me there if you need help with one of these modules (or help in general).
- Updated the LICENSE year. :fireworks:
=> git-url-parse 4.2.1 Added badges

README.md
Added GitPie in the "Where is this library used?" section :D
=> Added GitPie :smile:

CONTRIBUTING.md, DOCUMENTATION.md, README.md, package.json
=> git-url-parse 6.0.2

package.json
=> git-url-parse 6.0.5

README.md, package.json
- Updated the README.md following the new template. :memo:
- Add the [Patreon link](https://patreon.com/ionicabizau) in the README.md file. If you like what I'm doing, [supporting me](https://patreon.com/ionicabizau) would be awesome! Even **one dollar / month** would be helpful! Thanks! :heart:
=> git-url-parse 6.0.6

README.md, lib/index.js, package.json, test/index.js
Adds support for non-git usernames in stringified /cc #28 Thanks @cbargren! :cake:
=> git-url-parse 6.1.1

lib/index.js, test/index.js
=> Add FTP(S) support

LICENSE, lib/index.js, package.json, test/index.js
Add FTP(S) support. Thanks @jgrosso!
=> git-url-parse 6.2.0

.gitignore, README.md, lib/index.js, package.json, test/index.js
Add the .git suffix in the https urls. Thanks @gyandeeps!
=> git-url-parse 7.0.0

lib/index.js, test/index.js
Fixes https://github.com/IonicaBizau/git-url-parse/issues/45
=> Add support for Visual Studio Team Services URLs

lib/index.js, test/index.js
Fixes issue https://github.com/IonicaBizau/git-url-parse/issues/50
=> Handle VSTS URLs for repos/projects with whitespace in their names

lib/index.js, test/index.js
=> Add support for (GitLab-) Subgroups

lib/index.js, test/index.js
=> fix: include basic auth in http and https stringify

test/index.js
Test for https://github.com/IonicaBizau/git-url-parse/issues/141
=> test: failing test for custom SSH user

README.md, lib/index.js, package.json, test/index.js
Add edit filetype support /cc #146 -- thanks @ggdaltoso! :cake:
=> git-url-parse 13.1.0

LICENSE, package.json
fixed name and organization issue when parsing on the issue URL
=> git-url-parse 13.1.1

.github/FUNDING.yml, CONTRIBUTING.md, LICENSE, README.md, lib/index.js, package.json, test/index.js
Reencode owner and repo names -- thanks @lfcyja :cake:
=> git-url-parse 14.0.0

README.md, lib/index.js, package.json, test/index.js
fix parsing with 'blob' in file path /cc #168
=> git-url-parse 14.1.0

DOCUMENTATION.md, README.md, lib/index.js, package.json, test/index.js
Fixed parsing branch with slashes in its name /cc #170 Thanks @mixa1901 :cake:
=> git-url-parse 15.0.0

README.md, package.json, test/index.js
update to git-up 8.x.x -- thanks @richard-giraud! :cake:
=> git-url-parse 16.0.0

CONTRIBUTING.md, LICENSE, README.md, package.json
 - Update the documentation.
>  - Add the GitHub Sponsors link. 
>
> As always, I am very grateful to those supporting my projects! You can do that by donating via [PayPal](http://paypal.me/IonicaBizau) or via GitHub Sponsors.
>
> Thank you very much! :heart:
>
=> git-url-parse 16.0.1

README.md, lib/index.js
- https://github.com/IonicaBizau/git-up/pull/40
=> fix: port is string

DOCUMENTATION.md, README.md, lib/index.js, package.json
=> git-url-parse 16.0.2

lib/index.d.ts, package.json
Add types.
- https://github.com/IonicaBizau/git-up/pull/41
=> feat: add typescript types

README.md, package.json
=> git-url-parse 16.0.3
